import tiktoken

def get_tokens_count(text, encoding_name="cl100k_base", model_name=None):
    """
    Calculates the number of tokens in a given text based on the specified encoding or model.

    This function takes a text string and either an encoding name or a model name to determine
    the tokenization method. It returns the count of tokens generated by the encoding or model.
    Either `encoding_name` or `model_name` must be provided, but not both.

    Args:
        text (str): The text to be tokenized.
        encoding_name (str, optional): The name of the encoding to be used for tokenization.
                                       Only used if `model_name` is not provided. Defaults to "cl100k_base".
        model_name (str, optional): The name of the model whose encoding should be used for tokenization.
                                    Only used if `encoding_name` is not provided. Defaults to None.

    Raises:
        ValueError: If neither `model_name` nor `encoding_name` is provided.
        ValueError: If both `model_name` and `encoding_name` are provided.

    Returns:
        int: The count of tokens in the given text as per the specified encoding or model.
    """
    if model_name is None and encoding_name is None:
        raise ValueError("Either model or encoding must be provided")
    if model_name and encoding_name:
        raise ValueError("Both model and encoding should not be provided simultaneously")

    if model_name:
        encoding = tiktoken.encoding_for_model(model_name)
    else:  # encoding_name is not None
        encoding = tiktoken.get_encoding(encoding_name)

    return len(encoding.encode(text))
